name: "rings_103"
subject: "000"
experiment: "triplane_sdf"

dataroot: "/home/wanhu/workspace/gensdf/data/rings_test"

# 
seed: 42
resume: true


train:
  precision: 32
  max_epochs: 3_000
  check_val_every_n_epoch: 10

checkpoint:
  save_top_k: 1
  every_n_epochs: 10

dataset:
  _target_: dataloader.ring_dataset.CustomDataModule
  opt:
    dataroot: ${dataroot}
    subject: ${subject}
    num_sample: 50_000

    train_num_workers: 8
    val_num_workers: 0
    test_num_workers: 0


model:
  _target_: model.triplane_net.model.TriplaneSDF
  opt:
    # AABB: [-1,-1,-1]
    # triplane
    triplane:
      resolution: 256
      feature_dim: 32

    mlp_filters: [135,128,64,32,16,1]
    # 
    loss_fn: "l1" # "mse"
    last_op: "relu" # "sigmoid"
    lr_feature_init: 0.001
    feature_lr_step: 100
    feature_lr_gamma: 0.01

    lr_decoder_init: 0.001
    decoder_lr_step: 100
    decoder_lr_gamma: 0.01


hydra:
  run:
    dir: "outputs/${experiment}/${name}/${subject}"